#!/usr/bin/env bash
BASEDIR=$(echo "$(cd "$(dirname "$0")" && pwd)" | sed -E 's/(.*)\/script($|\/.*)/\1/')

cd $BASEDIR

docker build -t meetings/gearmand virt/gearmand
docker build -t meetings/mysql virt/mysql

rm -rf virt/gearslothd/src
git clone . virt/gearslothd/src
docker build -t meetings/gearslothd virt/gearslothd
