#!/usr/bin/env bash
BASEDIR=$(echo "$(cd "$(dirname "$0")" && pwd)" | sed -E 's/(.*)\/script($|\/.*)/\1/')

cd $BASEDIR

#script/build-local

./node_modules/.bin/mocha --recursive --ui tdd --reporter dot test/*/integration*
