#!/usr/bin/env bash
BASEDIR=$(echo "$(cd "$(dirname "$0")" && pwd)" | sed -E 's/(.*)\/script($|\/.*)/\1/')

cd $BASEDIR

script/build

./node_modules/.bin/mocha --recursive --ui tdd --reporter dot test/system
